# Why We use numPy array over List 

In [ ]:
# numPy(Memory) < list(Memory)
# numPy(Faster) > list(Faster)
# numPy(Convenience) >list(Convenience)
# numPy(Functionality) >list(Functionality)

# Why numPy arrays are faster than list in brief

In [ ]:
# numPy arrays are faster Because ->> numPy library has a special
# funcnality named vectorization in which it don't iterate the array
# element by element it goes with chunks so it is fast and c and 
# fortlin also has this quality 

# More On numPy 

In [49]:
import numpy as np
a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
a = [1,'ram' , 4.5]
b = np.array(a)
print(b)
print(type(b))



['1' 'ram' '4.5']
<class 'numpy.ndarray'>


<!-- numPy array can store only homogenious elements so it change all the elements in string by default
So we can change this default behaviour by giving an argument 
which is dtype  -->

In [6]:
import numpy as np
a = [1,'ram' , 4.5]
b = np.array(a , dtype = int)
print(b)
print(type(b))
# This will give an error because str can not change into int so
# we should remove that or change dtype 

ValueError: invalid literal for int() with base 10: 'ram'

In [7]:
import numpy as np
a = [1,5 , 4.5]
b = np.array(a , dtype = int)
print(b)
print(type(b))

[1 5 4]
<class 'numpy.ndarray'>


# OR change dtype to other 

In [9]:
import numpy as np
a = [1,'ram' , 4.5]
b = np.array(a , dtype = str)
print(b)

['1' 'ram' '4.5']


# Repeting list 

In [10]:
import numpy as np
a = [1, 2 , 4.5]
b = np.array(a*3)
print(b)

[1.  2.  4.5 1.  2.  4.5 1.  2.  4.5]


# function Ones

In [2]:
import numpy as np
b = np.ones(3  , dtype= int)
b
print(b)
# By default value is float 

[1 1 1]


# function Zeros

In [12]:
b = np.zeros(3  , dtype= int)
b
# By default value is float 

array([0, 0, 0])

# 2 - D Arrays Using zeros or ones

In [13]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
b = np.zeros((3,3) , dtype = int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Function Full 

In [15]:
b = np.full(3 , 5)
b
# By default integer 

array([5, 5, 5])

In [19]:
b = np.full(3 , 5 ,dtype = float) 
b
# By default integer value is 5 

array([5., 5., 5.])

In [17]:
b = np.full((3 , 5) , 5, dtype = float) 
b
# By default integer value is 5 

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# Function Empty 

In [20]:
b = np.empty(2)
b

array([4.24399158e-314, 8.48798317e-314])

In [21]:
b = np.empty((2 , 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
b = np.empty((2 , 3) , dtype = int)
b

array([[         0, 1075052544,          0],
       [1075052544,          0, 1075052544]])

# DIDNT GET THIS ORDER IN THIS LINE 

In [32]:
b = np.empty((2 , 3) , dtype = int ,order  = 'F')
b

array([[-1715897632,           0,      131074],
       [        332,           0,     5570652]])

#  Function Arrange
<!-- Syntax -> b = bp.arrange(start(Default 0) , stop(Mandatory) , step(By default 1) , dtype(By default int) )
It means we can not call the function without giving any argument  and stop is not included but start is included-->
<!-- 1 argument is required that is stop  -->

In [ ]:
# <!-- Syntax -> b = np.arrange(start(Default 0) , stop(Mandatory) , step(By default 1) , dtype(By default int) )
# It means we can not call the function without giving any argument  and stop is not included but start is included-->
# <!-- 1 argument is required that is stop  -->

In [51]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b = np.arange(2 , 10)
b    

array([2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = np.arange(2 , 10 , 2)
b

array([2, 4, 6, 8])

In [55]:
b = np.arange(2 , 10 , 2 ,dtype=float)
b

array([2., 4., 6., 8.])

# Function LineSpace 

<!-- b = np.linspace(start , stop , num(optional default 50) 
endpoint(By default True) retstep(Optional) 
dtype(by default float))

Description ->
1.)start value is mandatory
2.)end value is mandatory and depends on endpoint bool is
endpoint true then stop will included otherwise excluded
3.)num value this is optional by default value is 50 means we 
dont worry to give step value
4.) bydefault data type is float -->

In [58]:
b = np.linspace(1 , 10 , 5 , dtype=int)
b

array([ 1,  3,  5,  7, 10])

In [59]:
b = np.linspace(1 , 10 , 5 ,  endpoint = False, dtype=int)
b

array([1, 2, 4, 6, 8])

<!-- In above Example step difference is not equall  -->

# Function Identity 

In [60]:
b = np.identity(3)
b
# By default value is float type 
# We can Only get Square matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Function Identity 

In [62]:
b = np.eye(3)
b

# By default value is float type 
# We can get all type of  matrix 
# In eye we can make 3,4 identiy matrix but with identity function we can't 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Function random in (0,1)

In [76]:
b = np.random.rand(3)
b

array([0.53144354, 0.02435126, 0.13353261])

In [77]:
b = np.random.rand()
b
# ****************************This is amazing *********************

0.8517118417878022

In [64]:
b = np.random.rand(2,3)
b
# These value lies between 0 to 1 and uniformaly distributed 

array([[0.9269453 , 0.09684116, 0.42515129],
       [0.45314245, 0.13456495, 0.735121  ]])

# Function random  in different range(0,10)

In [65]:
b = np.random.rand(2,3)*10
b

array([[7.44002852, 0.86218895, 6.1425295 ],
       [4.68918259, 7.94435254, 6.72562676]])

# # Function random randint  in different range(0,10)

In [5]:
import numpy as np
b = np.random.randint(1 , 20  , (5,6) , dtype=int)
b

array([[16, 12,  5, 19,  7, 10],
       [15,  1,  1, 15, 16,  2],
       [ 4,  8,  7,  9, 11,  8],
       [17, 19, 18, 18, 10, 16],
       [ 1,  1,  7, 10,  6,  7]])

In [80]:
import numpy as np
b = np.eye(5,6,dtype=int)
for i in b:
    print(i)

# eye and identity functions both are same but we can create only square matrix in identity but in eye we can create rectanguler
# matrix also

[1 0 0 0 0 0]
[0 1 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]


In [1]:
import numpy as np
stepValue = 5/9
b = np.arange(0 , 5 , stepValue ,dtype=float)
for i in b:
    value = round(i , 2)
    print(value)

0.0
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


# Properties of numpy array 

In [ ]:
# Our NumPy stores 4 pointers which points to these qualitites about
# array 
# 1.)Data -> Memory location
# 2.)Shape -> Size of array
# 3.)dtype -> Data type 
# 4.)strides -> bytes /size of one variable which stored in array

# ONE D ARRAY

In [2]:
import numpy as np
b = [1,2,3,4]
c = np.array(b)
print(c)

[1 2 3 4]


In [3]:
print(c.data)
print(c.shape)
print(c.dtype)
print(c.strides)


(4,)
int32
(4,)


# 2D ARRAY

In [4]:
import numpy as np
b = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
c = np.array(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print(c.data)
print(c.shape)
print(c.dtype)
print(c.strides)

(3, 4)
int32
(16, 4)


In [ ]:
# In Last line first argument is  no of bytes to go in next line
# second is to go to next element in same line 

# Accessing Data from Numpy array

In [6]:
import numpy as np
b = [1,2,3,4]
d = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
c = np.array(b)
e = np.array(d)
print(c)
print(e)

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# For One d array 
print(c[1])
# slicing and last one is exclusive
print(c[1:4])

2
[2 3 4]


In [8]:
# For Two d array 
print(e[2][1])
# Both will same 
print(e[1,2])

10
7


# Slicing IN 2D array 

In [9]:
print(e[1][0:3])
# Both are same 
print(e[1 , 0:3])


[5 6 7]
[5 6 7]


In [15]:
print(e)
# print(e[1][0:3])
# # Both are same 
# print(e[1 , 0:3])

# **************************Important *************************
# print(e[0:3][3]) This will give error 
# print(e[0:3][3])
print(e[0:3][2])
print(e[0:3 , 2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 3  7 11]


# W should use this syntax in numpy arrays  print(e[0:3][2]) instead of this  print(e[0:3 , 2])

In [18]:
print(e)
print(e[0:3][0:2])
print(e[0:3 , 0:2])
# Both are different so it is important 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


# This is so much important 

# Mathmatical Operations on Simple 1 D list vs numpy 1D array 

In [23]:
import numpy as np
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
print(a)
print(b)
print(li)

[ 8 17 14  4 15]
[ 2 19  3 17 14]
[1, 2, 3, 4, 5]


# Adding 1 to all elements

In [25]:
# In Simple List

li = [i+1  for i in li]
print(li)

[2, 3, 4, 5, 6]


In [27]:
# In numpy array 

a = a + 1
print(a)

[10 19 16  6 17]


In [28]:
c = a + b
print(c)

[12 38 19 23 31]


In [29]:
d = a -b
print(d)

[  8   0  13 -11   3]


In [30]:
f = a*b
print(f)

[ 20 361  48 102 238]


In [31]:
g = a/b
print(g)

[5.         1.         5.33333333 0.35294118 1.21428571]


In [33]:
h = a//b
print(h)

[5 1 5 0 1]


In [34]:
m = a**b 
print(m)


[        100  -306639989        4096   193331200 -1138746399]


In [38]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
# Index at min 

print(a.max())
print(a.argmax())

[10 19 16  6 17]
68
13.6
6
3
19
1


#  Relational Operations 

In [39]:
a

array([10, 19, 16,  6, 17])

In [40]:
b

array([ 2, 19,  3, 17, 14])

In [41]:
a>b

array([ True, False,  True, False,  True])

In [42]:
a<b

array([False, False, False,  True, False])

In [43]:
a == b

array([False,  True, False, False, False])

# Logical Operations

All None zero values show true and zero showes false

In [44]:
a

array([10, 19, 16,  6, 17])

In [45]:
b

array([ 2, 19,  3, 17, 14])

In [46]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [48]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [49]:
print(np.logical_not(a))

[False False False False False]


# Mathmatical Operations on Simple 2 D list vs numpy 2D array 

In [61]:
import numpy as np
li = [[1,2,3],[4,5,6],[7,8,9]]
a = np.random.randint(1,20 , size = (3,3))
b = np.random.randint(1,20 , size = (3,3))
print(li)
print(a)
print(b)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[ 9 15 19]
 [12 18 14]
 [12 19 16]]
[[15 17  1]
 [ 4  4 10]
 [11  8  1]]


In [64]:
# Addting  to each element in simple list 

for i in li:
    print(i)
    for j in range(0 , len(i)):
        i[j] = i[j] + 1
    print(i)
print(li)

# Addting  to each element in numpy array 

a = a + 1
print(a)
b = b + 1
print(b)


[3, 4, 5]
[4, 5, 6]
[6, 7, 8]
[7, 8, 9]
[9, 10, 11]
[10, 11, 12]
[[4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[11 17 21]
 [14 20 16]
 [14 21 18]]
[[16 18  2]
 [ 5  5 11]
 [12  9  2]]


In [65]:
c = a+b
c

array([[27, 35, 23],
       [19, 25, 27],
       [26, 30, 20]])

In [66]:
c = a-b
c

array([[-5, -1, 19],
       [ 9, 15,  5],
       [ 2, 12, 16]])

In [67]:
c = a*b
c

array([[176, 306,  42],
       [ 70, 100, 176],
       [168, 189,  36]])

In [68]:
c = a/b
c

array([[ 0.6875    ,  0.94444444, 10.5       ],
       [ 2.8       ,  4.        ,  1.45454545],
       [ 1.16666667,  2.33333333,  9.        ]])

In [69]:
c = a//b
c

array([[ 0,  0, 10],
       [ 2,  4,  1],
       [ 1,  2,  9]], dtype=int32)

In [70]:
c = a**b
c

array([[  772479681, -1482188255,         441],
       [     537824,     3200000,           0],
       [  344068096,  -288903179,         324]], dtype=int32)

In [ ]:
# print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
# Index at min 

print(a.max())
print(a.argmax())

#  Relational Operations 

In [72]:
a

array([[11, 17, 21],
       [14, 20, 16],
       [14, 21, 18]])

In [73]:
b

array([[16, 18,  2],
       [ 5,  5, 11],
       [12,  9,  2]])

In [74]:
a>b

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [76]:
a<b

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [77]:
a == b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Logical Operations

0 represents false and 1 represents 0

In [78]:
a

array([[11, 17, 21],
       [14, 20, 16],
       [14, 21, 18]])

In [79]:
b

array([[16, 18,  2],
       [ 5,  5, 11],
       [12,  9,  2]])

In [80]:
print(np.logical_or(a,b))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [81]:
print(np.logical_and(a,b))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [82]:
print(np.logical_not(a))

[[False False False]
 [False False False]
 [False False False]]


# Some New In Numpy array 

In [83]:
a

array([[11, 17, 21],
       [14, 20, 16],
       [14, 21, 18]])

In [84]:
b

array([[16, 18,  2],
       [ 5,  5, 11],
       [12,  9,  2]])

In [85]:
print(b>10)

[[ True  True False]
 [False False  True]
 [ True False False]]


In [116]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)
print(type(new_arr))
print(type(b))

[ True  True  True  True  True False]
[17 13 17 16 19]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [115]:
new_arr = b[b>10]
print(new_arr)
# This will give those elements and pust in an array which are greate 10 in np array b 

[17 13 17 16 19]


In [96]:
new_arr1 = b[(b>10) & (b<18)]
print(new_arr1)

[16 11 12]


In [98]:
b
c = b

In [101]:
c[:3] = 19
print(c)
c[c>15] = 100
print(c)

[[19 19 19]
 [19 19 19]
 [19 19 19]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [104]:
import numpy as np
b = np.random.randint(0,20,6)
b

array([17, 13, 17, 16, 19,  9])

In [106]:
print(b[b==17])

[17 17]


# Where Function 

In [108]:
indexes = np.where(b==17)
indexes
# This indexes is a two D list 

(array([0, 2], dtype=int64),)

In [110]:
a = np.random.randint(0,20,6)
b == np.random.randint(0,20,6)
print(a)
print(b)

[14 16  7  5 12 14]
[17 13 17 16 19  9]


In [118]:
import numpy as np
l = [1,2,0,0,4,0]
a = np.array(l)
x = np.where(a != 0)
print(x)
for i in x:
    for j in i:
        print(j , end = " ")

(array([0, 1, 4], dtype=int64),)
0 1 4 

# Important WOOOOOOEEEE **********************

In [1]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])


x = np.where(height>155)
y = age[x]
print(y)

# We can do this , this is amazing thing 

[15 19 20 21 22 23 16 18 20 15 17]


# Boolen Indexing Using 2D Arrays 

In [14]:
import numpy as np
a = np.random.randint(0 , 20 , (5,6))
a

array([[ 5, 15,  4, 13,  0, 16],
       [14, 16, 15, 13, 10,  6],
       [10,  6, 18,  6,  2,  9],
       [ 6, 13,  4, 15, 11, 15],
       [17, 10, 11, 16,  9,  8]])

In [16]:
a>10

array([[False,  True, False,  True, False,  True],
       [ True,  True,  True,  True, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False,  True,  True,  True],
       [ True, False,  True,  True, False, False]])

 We can save  this ans  in an array 

In [17]:
bool_arr = a>10
print(bool_arr)

[[False  True False  True False  True]
 [ True  True  True  True False False]
 [False False  True False False False]
 [False  True False  True  True  True]
 [ True False  True  True False False]]


In [18]:
ans = a[bool_arr]
print(ans)
# All true values will store in ans 

[15 13 16 14 16 15 13 18 13 15 11 15 17 11 16]


In [20]:
print(a[a>10])

[15 13 16 14 16 15 13 18 13 15 11 15 17 11 16]


In [21]:
b = a
b

array([[ 5, 15,  4, 13,  0, 16],
       [14, 16, 15, 13, 10,  6],
       [10,  6, 18,  6,  2,  9],
       [ 6, 13,  4, 15, 11, 15],
       [17, 10, 11, 16,  9,  8]])

In [22]:
b[bool_arr] = 100
b
# Where where bool_arr is true the value will changed in b 

array([[  5, 100,   4, 100,   0, 100],
       [100, 100, 100, 100,  10,   6],
       [ 10,   6, 100,   6,   2,   9],
       [  6, 100,   4, 100, 100, 100],
       [100,  10, 100, 100,   9,   8]])

In [ ]:
# The length of bool_arr and b should be same otherwise it will give
# error

In [41]:
b = np.random.randint(0 , 200 , (5,6))
b

array([[116, 194, 170, 180, 123,  58],
       [ 90, 153,  25,  36,  54, 179],
       [  3, 125,  79,  41,  21, 111],
       [ 69, 153,  77, 166,  24, 174],
       [ 36,  97, 138, 175,  84,  25]])

In [42]:
bool_arr = (b[ : ,3] == 175)
bool_arr

array([False, False, False, False,  True])

In [44]:
print([b[ : ,3 ])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3418101911.py, line 1)

In [40]:
b[bool_arr , 3] = 99
b

array([[156, 159, 171,  84,  46,  26],
       [141, 137,  80,  82,  16, 194],
       [179,  95,  99, 122,  99, 122],
       [102,  66,   5, 171,  87, 161],
       [ 99,  99,  99,  99,  99,  99]])

In [2]:
 ## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np
with open('terrorismData.csv') as file_obj:
    file_data = csv.DictReader(file_obj , skipinitialspace = True)
    date = []
    for row in file_data:
        killed = row["Killed"]
        if(killed != ''):
            killed = int(float(killed));
        else:
            killed = 0
        wounded = row["Wounded"]
        if(wounded != ''):
             wounded = int(float(wounded));
        else:
            wounded = 0
        # print(row['Month'])
        # print(type(row['Month']))
        date.append( [ int(float(row['Month'])) , int(float(row['Year'])) , killed ,  wounded  , row["City"] , row["Group"] ])
                         
npdate = np.array(date)
# print(npdate)

npdate = npdate[npdate[:,1]==1999]
npdate = npdate[npdate[:,0]>=5]
npdate = npdate[npdate[:,0]<=7]
print(npdate)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6235: character maps to <undefined>

In [6]:
x = "March 18 2010"
print(len(x))
print(x[9:])

13
2010
